USE master
GO

DROP DATABASE HotelManagementSystem
GO

CREATE DATABASE HotelManagementSystem
GO

USE HotelManagementSystem
GO


CREATE TABLE RStatus
(
    Status VARCHAR(100) PRIMARY KEY,
    Description NVARCHAR(MAX)
)
GO

--Rooms_Type
CREATE TABLE RoomTypes
(
    RType VARCHAR(100) NOT NULL PRIMARY KEY,
	RTBedCount TINYINT NOT NULL DEFAULT 1,
	RTMaxGuests TINYINT NOT NULL DEFAULT 1,
	RTDescription NVARCHAR(MAX)
)
GO

--Rooms
CREATE TABLE Rooms
(
    RId VARCHAR(50) NOT NULL PRIMARY KEY,
	RType VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES RoomTypes(RType),
    RStatus VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES RoomStatus(RStatus),
	RPricePerNight DECIMAL(10,2) NOT NULL CHECK (RPricePerNight >= 0) DEFAULT 100,
	RDescription NVARCHAR(MAX)
)
GO


CREATE TABLE Customers
(
    CID VARCHAR(100) PRIMARY KEY,   
    CName NVARCHAR(100) NOT NULL,        
    CGender CHAR(6) CHECK (CGender IN ('Male', 'Female', 'Other')) NOT NULL,  
    CPhone VARCHAR(15) UNIQUE NOT NULL,
    CEmail VARCHAR(100) UNIQUE,
    CAddress NVARCHAR(255),         
    CType CHAR(20) CHECK (CType IN ('Regular', 'VIP', 'New')) DEFAULT 'New'
)
GO

CREATE TABLE EmployeeRole (
    ERole VARCHAR(100) PRIMARY KEY,   
    ERDescription NVARCHAR(100)
)
GO

CREATE TABLE Employees 
(
    EID VARCHAR(100) PRIMARY KEY,   
    EName NVARCHAR(100) NOT NULL,         
    EGender CHAR(6) CHECK (EGender IN ('Male', 'Female', 'Other')) NOT NULL,  
    EPhone VARCHAR(15) UNIQUE NOT NULL,   
    EEmail VARCHAR(100) UNIQUE ,  
    EAddress NVARCHAR(255) ,          
    EStatus CHAR(10) CHECK (EStatus IN ('Active', 'Inactive', 'On Leave')) NOT NULL,  
    ERole VARCHAR(100) FOREIGN KEY REFERENCES EmployeeRole(ERole)                 
)
GO

CREATE TABLE [Services] 
(
    SName VARCHAR(100) PRIMARY KEY,
    SPrice DECIMAL(10,2) NOT NULL CHECK (SPrice >= 0),
    SDescription NVARCHAR(MAX)
);
GO


CREATE TABLE BookingStatus
(
	BStatus VARCHAR(100) PRIMARY KEY,
	BKDescription NVARCHAR(MAX)
)
GO

CREATE TABLE PaymentMethod
(
	PMethod VARCHAR(100) PRIMARY KEY,
	Description NVARCHAR(MAX)
)
GO

CREATE TABLE PaymentStatus
(
    PStatus VARCHAR(100) PRIMARY KEY,
    Description NVARCHAR(MAX)
)
GO

CREATE TABLE Bookings (
    BID VARCHAR(100) PRIMARY KEY,
	RId VARCHAR(50) FOREIGN KEY REFERENCES Rooms(RId),
    CID VARCHAR(100) NOT NULL FOREIGN KEY (CID) REFERENCES Customers(CID),
	EID VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES Employees(EID),
    BTimeCheckIn DATETIME NOT NULL,  
    BTimeCheckOut DATETIME NOT NULL, 
    BStatus VARCHAR(100) NOT NULL,  
    BCreateAt DATETIME DEFAULT GETDATE(),
	
);
GO

CREATE TABLE ServiceUsage 
(
    BID VARCHAR(100) PRIMARY KEY FOREIGN KEY (BID) REFERENCES Bookings(BID), 
    SUDate DATETIME NOT NULL DEFAULT GETDATE(),
	PMethod VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES PaymentMethod(PMethod),
    PStatus VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES PaymentStatus(PStatus)
);
GO

CREATE TABLE ServiceUsageDetail 
(
    BID VARCHAR(100) FOREIGN KEY REFERENCES ServiceUsage(BID),
    SName VARCHAR(100) FOREIGN KEY REFERENCES Services(SName),
	PRIMARY KEY (BID, SName),

	EID VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES Employees(EID),
    UnitPrice DECIMAL(10,2) NOT NULL CHECK (UnitPrice >= 0),
    Quantity INT NOT NULL CHECK (Quantity > 0),
    Discount DECIMAL(5,2) DEFAULT 0 CHECK (Discount BETWEEN 0 AND 100)    
);
GO

CREATE TABLE BookingPayments
(
    BID VARCHAR(100) PRIMARY KEY FOREIGN KEY (BID) REFERENCES Bookings(BID),
    EID VARCHAR(100) FOREIGN KEY (EID) REFERENCES Employees(EID),
    BPAmount DECIMAL(10,2) NOT NULL CHECK (BPAmount >= 0),
    BPDate DATETIME DEFAULT GETDATE(),
    PMethod VARCHAR(100) FOREIGN KEY (PMethod) REFERENCES PaymentMethod(PMethod),
    PStatus VARCHAR(100) FOREIGN KEY (PStatus) REFERENCES PaymentStatus(PStatus)
);
GO