//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string BID { get; set; }
        public string RId { get; set; }
        public string CID { get; set; }
        public string EID { get; set; }
        public System.DateTime BTimeCheckIn { get; set; }
        public System.DateTime BTimeCheckOut { get; set; }
        public string BStatus { get; set; }
        public Nullable<System.DateTime> BCreateAt { get; set; }
    
        public virtual Booking_Payments Booking_Payments { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Room Room { get; set; }
        public virtual ServiceUsage ServiceUsage { get; set; }
    }
}
