//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bookings()
        {
            this.BookingPayments = new HashSet<BookingPayments>();
            this.ServiceUsage = new HashSet<ServiceUsage>();
        }
    
        public string BId { get; set; }
        public string RId { get; set; }
        public string CId { get; set; }
        public string EId { get; set; }
        public System.DateTime BTimeCheckIn { get; set; }
        public System.DateTime BTimeCheckOut { get; set; }
        public string BStatus { get; set; }
        public Nullable<System.DateTime> BCreateAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingPayments> BookingPayments { get; set; }
        public virtual BookingStatus BookingStatus { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Rooms Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceUsage> ServiceUsage { get; set; }
    }
}
