//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Online
    {
        public System.DateTime CreateAt { get; set; }
        public string CCCD { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<System.DateTime> TGianNhanPhong { get; set; }
        public Nullable<System.DateTime> TGianTraPhong { get; set; }
        public string LoaiPhong { get; set; }
    
        public virtual RType RType { get; set; }
    }
}
