//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using DataTransferObject;
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public string BPId { get; set; }
        public string BId { get; set; }
        public string EId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PMethod { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public static Payments Convert(PaymentDTO paymentDTO)
        {
            return new Payments
            {
                BPId = paymentDTO.BPId,
                BId = paymentDTO.BId,
                EId = paymentDTO.EId,
                Amount = paymentDTO.Amount,
                Date = DateTime.Now,
                PMethod = paymentDTO.PMethod
            };
        }
    }
}
