//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using DataTransferObject;
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rooms()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public string RId { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public decimal PricePerNight { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual RStatus RStatus { get; set; }
        public virtual RType RType { get; set; }

        public void ConvertTo_From(RoomDTO roomDTO)
        {
            this.RId = roomDTO.RId;
            this.Type = roomDTO.RType;
            this.Status = roomDTO.RStatus;
            this.PricePerNight = roomDTO.RPricePerNight;
            this.Description = roomDTO.RDescription;
        }
    }
}
