//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using DataTransferObject;
    using System;
    using System.Collections.Generic;

    public partial class ServiceUsageDetail
    {
        public string SUId { get; set; }
        public string SName { get; set; }
        public string EId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreateAt { get; set; }

        public virtual Employees Employees { get; set; }
        public virtual Services Services { get; set; }
        public virtual ServiceUsage ServiceUsage { get; set; }

        public static ServiceUsageDetail Convert(ServiceUsageDetailDTO serviceUsageDetailDTO)
        {
            return new ServiceUsageDetail
            {
                SUId = serviceUsageDetailDTO.SUId,
                SName = serviceUsageDetailDTO.SName,
                EId = serviceUsageDetailDTO.EId,
                Quantity = serviceUsageDetailDTO.Quantity,
                CreateAt = DateTime.Now
            };
        }
    }
}
