//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceUsage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceUsage()
        {
            this.ServiceUsageDetails = new HashSet<ServiceUsageDetail>();
        }
    
        public string BID { get; set; }
        public System.DateTime SUDate { get; set; }
        public string PMethod { get; set; }
        public string PStatus { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual Payment_Status Payment_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceUsageDetail> ServiceUsageDetails { get; set; }
    }
}
