//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceUsageDetail
    {
        public string BID { get; set; }
        public string SName { get; set; }
        public string EID { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceUsage ServiceUsage { get; set; }
    }
}
